# Generated by Django 4.1.7 on 2023-05-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color_detect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pred_images',
            old_name='image',
            new_name='photo',
        ),
    ]
